sylius_resource:
    resources:
        positibe.user:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\User
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Positibe\Bundle\CoreBundle\Repository\EntityRepository
                form: Positibe\Bundle\UserBundle\Form\Type\UserFormType

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:        "%sender_address%"
        sender_name:    "%sender_name%"
    registration:
        confirmation:
            enabled: true
    profile:
        form:
            type: Positibe\Bundle\UserBundle\Form\Type\ProfileFormType

ivory_ck_editor:
    configs:
        simple:
            toolbar: basic
            filebrowserUploadRoute: "positibe_media_upload"
            filebrowserBrowseRoute: "elfinder"
            contentsCss: "css/compiled/main.css"