parameters:
    positibe_user_form_class: Positibe\Bundle\UserBundle\Form\Type\UserFormType
    user_class: App\Entity\User

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    firewall_name: main
    user_class: "%user_class%"
    from_email:
        address:        "%sender_address%"
        sender_name:    "%sender_name%"
    registration:
        confirmation:
            enabled: true
    profile:
        form:
            type: Positibe\Bundle\UserBundle\Form\Type\ProfileFormType