services:
#    positibe_user.example:
#        class: Positibe\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Positibe\Bundle\UserBundle\Form\Type\UserFormType:
        public: false
        tags:
            - { name: form.type }