<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\UserBundle\Form\Type;

use Ivory\CKEditorBundle\Form\Type\CKEditorType;
use Positibe\Bundle\MediaBundle\Form\Type\ImageType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class UserFormType
 * @package Positibe\Bundle\UserBundle\Form\Type
 */
class UserFormType extends AbstractType
{
    protected $roles = [];

    /**
     * @return array
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * @param array $roles
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'username',
                null,
                [
                    'label' => 'Usuario:',
                    'help' => 'Nombre de usuario',
                ]
            )
            ->add('email', null, ['label' => 'Correo:'])
            ->add('name', null, ['label' => 'Nombre(s) y apellidos:'])
            ->add('sign', CKEditorType::class, ['label' => 'Firma:'])
            ->add('avatar', ImageType::class, array('label' => 'Avatar:'))
            ->add(
                'roles',
                ChoiceType::class,
                [
                    'choices' => array_combine($this->roles, $this->roles),
                    'multiple' => true,
                    'expanded' => true,
                    'label' => 'Permisos especiales:',
                ]
            )
            ->add('plain_password', PasswordType::class, ['label' => 'Nueva contraseña:', 'required' => false])
            ->add('enabled', null, ['label' => 'Usuario habilitado', 'data' => true, 'required' => false]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function setDefaultOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Positibe\Bundle\UserBundle\Entity\User',
            )
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'app_user';
    }
}
